// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWJ2a00-SNOD5szGO_1BDdnsX1stoaXHo',
    appId: '1:515166640880:web:997aff80cc4b166f39c035',
    messagingSenderId: '515166640880',
    projectId: 'qlct-125e8',
    authDomain: 'qlct-125e8.firebaseapp.com',
    storageBucket: 'qlct-125e8.firebasestorage.app',
    measurementId: 'G-4FVW9XNJY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUXJEIrvsc1Y69LUa6Ehja_GWuI5bdrgY',
    appId: '1:515166640880:android:9c75c44e899109e239c035',
    messagingSenderId: '515166640880',
    projectId: 'qlct-125e8',
    storageBucket: 'qlct-125e8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWJ2a00-SNOD5szGO_1BDdnsX1stoaXHo',
    appId: '1:515166640880:web:dffe8aa18bb01e2f39c035',
    messagingSenderId: '515166640880',
    projectId: 'qlct-125e8',
    authDomain: 'qlct-125e8.firebaseapp.com',
    storageBucket: 'qlct-125e8.firebasestorage.app',
    measurementId: 'G-7JDEEN03PL',
  );
}
